### ISSUE TITLE
Make sure bots and other things work OK with rakudo/issues

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1199]
A list of things to tweak:

- [x] synopsebot – [done](https://github.com/perl6/synopsebot/commit/c93e528c35ac22b08f901926871150ea72af905e)
- [ ] https://fail.rakudo.party
- [x] add all commonly-used tags as [labels](https://github.com/rakudo/rakudo/labels)
- [x] RT weekly → RT/GH weekly (done, [example](https://gist.github.com/AlexDaniel/5c4030253c6b90cf4b1ce2ddd6860323))

… more?

**Comment by AlexDaniel** [comment]
FWIW I've opened this issue tracker because this was the last drop for me: https://irclog.perlgeek.de/perl6-dev/2017-10-22#i_15336853
It's totally not OK that users are reluctant to file bug reports because the tracker refuses to work with them. Even if we decide that rakudo/issues should not be used, we still need a backup for cases like this. GitHub is ok for that for sure.

**Comment by AlexDaniel** [comment]
> add all commonly-used tags as labels

Everyone can add a label just by typing a name that does not exist, it'll create a new label automatically. That part is resolved I think.

**Comment by AlexDaniel** [comment]
Just for reference:
* https://rt.perl.org/Ticket/Display.html?id=128520
* https://github.com/rakudo/rakudo/issues/1598

**Comment by JJ** [comment]
The thing left in this issue no longer exists; maybe it should be substituted by Blin?

**Comment by AlexDaniel** [comment]
Actually, fail.rakudo.party is now https://github.com/Raku/old-issue-tracker. Indeed, this can be closed.
