### ISSUE TITLE
Rakudo repo cleanup (mainly tools/ directory)

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1252]
In a comment section of https://github.com/rakudo/rakudo/commit/99f38f9fe43fa488421e05bf21d7863b1c220907 it was mentioned that rakudo git repo has some scripts that are likely unused, or simply do not belong to the repo. Let's assess the situation and clean it up a little bit.

**⚠ Feel free to edit this post. Mark a file with ✓ if it was moved, removed or if it's decided that it should stay.  Replace “⁇” with any helpful commentary.**

- [ ] ``tools``
- [ ] ``├── autounfudge.pl`` – ⁇
- [x] ``├── available-pm-names.pl6`` – deleted in 825a8b0d093ed4f75179cd1c4a2613d583939752
- [ ] ``├── benchmark.pl`` – ⁇
- [ ] ``├── build``
- [x] ``│   ├── common_bootstrap_sources`` – ⁇
- [ ] ``│   ├── create-jvm-runner.pl`` – ⁇
- [ ] ``│   ├── create-moar-runner.pl`` – ⁇
- [x] ``│   ├── gen-cat.nqp`` – ⁇
- [x] ``│   ├── gen-version.pl`` – ⁇
- [x] ``│   ├── install-core-dist.pl`` – ⁇
- [ ] ``│   ├── jvm_core_d_sources`` – ⁇
- [ ] ``│   ├── jvm_core_sources`` – ⁇
- [x] ``│   ├── Makefile-common-macros.in`` – ⁇
- [x] ``│   ├── Makefile-common-rules.in`` – ⁇
- [x] ``│   ├── Makefile-JVM.in`` – ⁇
- [x] ``│   ├── Makefile-Moar.in`` – ⁇
- [ ] ``│   ├── makeMAGIC_INC_DEC.pl6`` – ⁇
- [ ] ``│   ├── makeNATIVE_ARRAY.pl6`` – ⁇
- [ ] ``│   ├── makeNATIVE_SHAPED_ARRAY.pl6`` – ⁇
- [ ] ``│   ├── makeSLICE.pl6`` – ⁇
- [ ] ``│   ├── makeUNIPROP.pl6`` – ⁇
- [x] ``│   ├── missing-commits.pl6`` – compared to [releasable](https://github.com/perl6/whateverable/wiki/Releasable) the script probably doesn't do enough, so either delete or move to *rakudo/release* repo (deleted in 6ec6f1eb2945f686767a40c1c06415cab4b4abbf)
- [ ] ``│   ├── moar_core_d_sources`` – ⁇
- [ ] ``│   ├── moar_core_sources`` – ⁇
- [ ] ``│   ├── nqp-jvm-rr.pl`` – ⁇
- [ ] ``│   ├── NQP_REVISION`` – this file should absolutely stay, but is it the best place for it?
- [ ] ``│   └── upgrade-repository.pl`` – ⁇
- [ ] ``├── build-localtest.pl`` – ⁇
- [x] ``├── commit-stats.pl`` – deleted in 028b7d22ca4b840e8ff612165524276d119d5e27
- [ ] ``├── contributors.pl6`` – part of the release process. Move to *rakudo/release* repo?
- [ ] ``├── create-release-announcement.pl6`` – part of the release process. Move to *rakudo/release* repo?
- [ ] ``├── CREDITS.pl6`` – ⁇
- [ ] ``├── install-dist.pl`` – ⁇
- [x] ``├── lib``
- [x] ``│   └── NQP``
- [x] ``│       └── Configure.pm`` – used by Configure.pl
- [ ] ``├── perl6-limited.pl`` – ⁇
- [x] ``├── progress-graph.pl`` – deleted in 5baede5915980a6fe1db9a33b5253248282378b6
- [ ] ``├── rakudo-swarm.config`` – ⁇
- [ ] ``├── release-dates.pl`` – it is used once in forever. Let's golf it and then it can be included in the release docs
- [ ] ``├── update-passing-test-data.pl`` – ⁇
- [x] ``├── update-tai-utc.pl`` –  updates leap seconds
- [ ] ``└── util``
- [ ] ``    └── perlcritic.conf`` – ⁇

**Comment by tbrowder** [comment]
lib/NQP/Configure.pm should be modded, along with Configure.pl, so tha a user can, optionally, use another github account for a build. See the issue I am sbout to make.

**Comment by AlexDaniel** [comment]
This is old. If I continued to work on this I'd start from scratch.
