### ISSUE TITLE
Unicode 11 Bump Issue tracking

### ISSUE THREAD

**Issue by samcv** [rakudo/rakudo#2337]
Making this an issue so we can make sure to track things arising from the Unicode 11 bump in one place.

- [ ] Regenerate Property mappings with makeUNIPROP.p6
- [ ] Update any roast tests which indicate an old version in roast/docs/unicode-generated-tests.asciidoc
- [ ] Semi related: update S32-encoding/registry.t in roast https://github.com/perl6/roast/issues/477

**Comment by samcv** [comment]
Also see https://github.com/perl6/roast/issues/477 on another related item regarding the bump.

**Comment by samcv** [comment]
I think this can be closed now.
