### ISSUE TITLE
Pre-2018.11 toasting

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2451]
Here are some quick preliminary results from [Blin](https://github.com/perl6/Blin):

https://gist.github.com/AlexDaniel/3296f8cbc5dcc9ca55272114f25d5087#file-bisected

Some examples:

* IO::Glob “Too late to switch language version. Must be used as the very first statement.”
* Path::Router “Too late to switch language version. Must be used as the very first statement.”
* File::Compare “Too late to switch language version. Must be used as the very first statement.”

I'll try to improve Blin shortly so that it shows the output. For now that's the only info I can easily share

Please submit PRs to affected modules.

TODO list:
- [x] [AWS::Session](https://modules.perl6.org/dist/AWS::Session) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [App::Tasks](https://modules.perl6.org/dist/App::Tasks) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [Archive::SimpleZip](https://modules.perl6.org/dist/Archive::SimpleZip) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [AttrX::Mooish](https://modules.perl6.org/dist/AttrX::Mooish) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [Binary::Structured](https://modules.perl6.org/dist/Binary::Structured) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [Compress::Snappy](https://modules.perl6.org/dist/Compress::Snappy) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [Crust](https://modules.perl6.org/dist/Crust) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [DOM::Tiny](https://modules.perl6.org/dist/DOM::Tiny) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [File::Compare](https://modules.perl6.org/dist/File::Compare) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [File::Find::Duplicates](https://modules.perl6.org/dist/File::Find::Duplicates) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [Fortran::Grammar](https://modules.perl6.org/dist/Fortran::Grammar) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [Getopt::ForClass](https://modules.perl6.org/dist/Getopt::ForClass) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [Getopt::Std](https://modules.perl6.org/dist/Getopt::Std) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [HTTP::Request::FormData](https://modules.perl6.org/dist/HTTP::Request::FormData) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [HTTP::Request::Supply](https://modules.perl6.org/dist/HTTP::Request::Supply) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [HTTP::Server::Ogre](https://modules.perl6.org/dist/HTTP::Server::Ogre) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [Hash::MultiValue](https://modules.perl6.org/dist/Hash::MultiValue) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [Hematite](https://modules.perl6.org/dist/Hematite) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [IO::Glob](https://modules.perl6.org/dist/IO::Glob) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [JSON::WebToken](https://modules.perl6.org/dist/JSON::WebToken) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [Lingua::EN::Sentence](https://modules.perl6.org/dist/Lingua::EN::Sentence) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [Lingua::Unihan](https://modules.perl6.org/dist/Lingua::Unihan) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [Path::Router](https://modules.perl6.org/dist/Path::Router) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [Perl6::Maven](https://modules.perl6.org/dist/Perl6::Maven) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [Perl6::Parser](https://modules.perl6.org/dist/Perl6::Parser) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8 TICKET: https://github.com/rakudo/rakudo/issues/2499
- [x] [Perl6::Tidy](https://modules.perl6.org/dist/Perl6::Tidy) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8 TICKET: https://github.com/rakudo/rakudo/issues/2499
- [x] [Pod::TreeWalker](https://modules.perl6.org/dist/Pod::TreeWalker) – Fail, Bisected: 5aba3e962e1315521c3d4b8dea1c1f825f278602
- [x] [Prime::Factor](https://modules.perl6.org/dist/Prime::Factor) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [SQL::Lexer](https://modules.perl6.org/dist/SQL::Lexer) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [Serialize::Naive](https://modules.perl6.org/dist/Serialize::Naive) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [Shell::Capture](https://modules.perl6.org/dist/Shell::Capture) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [Sort::Naturally](https://modules.perl6.org/dist/Sort::Naturally) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [StrictNamedArguments](https://modules.perl6.org/dist/StrictNamedArguments) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [Template::Anti](https://modules.perl6.org/dist/Template::Anti) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [Test::Deeply::Relaxed](https://modules.perl6.org/dist/Test::Deeply::Relaxed) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [Tinky::JSON](https://modules.perl6.org/dist/Tinky::JSON) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8 TICKET: https://github.com/rakudo/rakudo/issues/2498
- [x] [WWW::vlc::Remote](https://modules.perl6.org/dist/WWW::vlc::Remote) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [Web::RF](https://modules.perl6.org/dist/Web::RF) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [bamboo](https://modules.perl6.org/dist/bamboo) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8
- [x] [if](https://modules.perl6.org/dist/if) – Fail, Bisected: 46ef0ea08cae96db25c7b5a9543ba696034408c8

**Comment by AlexDaniel** [comment]
> \<AlexDaniel\> timotimo: there's only one non v6.d-related result: https://gist.github.com/AlexDaniel/3296f8cbc5dcc9ca55272114f25d5087#file-bisected-L27
> \<timotimo\> that's just when @.allowed was removed from Pod::Block::Code

**Comment by thundergnat** [comment]
Prime::Factor and Sort:Naturally should both be ok now. (both my modules, updated yesterday).

**Comment by AlexDaniel** [comment]
@thundergnat thanks, marked!

**Comment by lizmat** [comment]
/me is not seeing any failure on `App::Tasks` ?

**Comment by AlexDaniel** [comment]
@lizmat I think it was fixed. The git repo is inaccessible so I can't show the exact commit, but the CPAN distribution was updated around the time when this ticket was created. So it's likely fixed, yes.

**Comment by AlexDaniel** [comment]
OK, I submitted a few PRs:

* https://github.com/avuserow/perl6-binary-structured/pull/5
* https://github.com/avuserow/perl6-compress-snappy/pull/10
* https://github.com/labster/perl6-File-Compare/pull/9
* https://github.com/ppentchev/perl6-Test-Deeply-Relaxed/pull/3
* https://github.com/dmaestro/SQL-Lexer/pull/1
* https://github.com/ppentchev/Shell-Capture/pull/2
* https://github.com/sergot/bamboo/pull/7
* https://github.com/ppentchev/Serialize-Naive/pull/2
* https://github.com/fayland/perl6-Lingua-Unihan/pull/3
* https://github.com/dginev/perl6-Lingua-EN-Sentence/pull/7
* https://github.com/jamesalbert/JSON-WebToken/pull/3

I think remaining modules have more serious issues, but currently I'm not certain.

**Comment by AlexDaniel** [comment]
That's it for now! I'll do another run later, blin.
