### ISSUE TITLE
[WIP] Blin 2019.02

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2705]
This ticket is primarily for myself.

Raw results here: https://gist.github.com/AlexDaniel/803489b81e17c82b64e4d26d3a9b2524

- [x] ANTLR4::Grammar – Fail, Bisected: eb3917c260bce1cb56e2ee40abebd12c4dbcd9b2 https://github.com/rakudo/rakudo/issues/2704
- [x] Algorithm::LibSVM – Fail, Bisected: 685f6cc3b6af59a7df92fcd33eef5f1cc36e34de https://github.com/rakudo/rakudo/issues/2642
- [x] Astro::Sunrise – Fail, Bisected: d0a3fec997cffa77100af47a666c11166f705b0b b378a157ebc000c35ed9ea2702050ad4de6d23a4 https://github.com/rakudo/rakudo/issues/2618
- [x] Backtrace::AsHTML – Fail, Bisected: 5b231e09991f13064c9e1a2d63bf294a236abdea https://github.com/moznion/p6-Backtrace-AsHTML/pull/10
- [x] Font::FreeType – Fail, Bisected: ee2238f731f548861e26d745ea1be2ba22d24f4e https://github.com/rakudo/rakudo/issues/2706
- [x] JSON::WebToken – Fail, Bisected: b378a157ebc000c35ed9ea2702050ad4de6d23a4 https://github.com/rakudo/rakudo/issues/2641
- [x] NativeHelpers::Blob – Fail, Bisected: 51f035c4e230e6849024d382e0f4197a653de78c https://github.com/rakudo/rakudo/issues/2703
- [x] P6Repl::Helper – Fail, Bisected: 66f8ee0fbbf9235884439048b04c39a017bae876 https://github.com/kjkuan/P6Repl-Helper/pull/1
- [x] Red – Fail, Bisected: 3d3578b6058d552b4842952ad1bfdbd9ed7d3c5f https://github.com/rakudo/rakudo/issues/2640

**Comment by AlexDaniel** [comment]
Some new stuff I'm investigating:

- [ ] Crane – Fail, Bisected: 616b757a461faa90d889b77d53e093e70280f059
- [ ] Jupyter::Kernel – Fail, Bisected: 616b757a461faa90d889b77d53e093e70280f059
- [ ] PDF::Font::Loader – Fail, Bisected: f98a70cab406794257ab2ad02a38721436ff9d19
