### ISSUE TITLE
[WIP] Blin 2019.06

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2998]
This ticket is primarily for the release manager.

Raw results here: https://usercontent.irccloud-cdn.com/file/IBY6c9W1/p6out.tar.xz

- [x] [App::ecogen](https://modules.perl6.org/dist/App::ecogen) – Fail, Bisected: b7e0e894d79bbcc73d54c5476a3a5b51ee5ab02e https://github.com/ugexe/Perl6-App--ecogen/commit/2d89a00898bd76ec05965ef00a1169d0cca677a9
- [x] [Digest::BubbleBabble](https://modules.perl6.org/dist/Digest::BubbleBabble) – Fail, Bisected: 35b69f074b9db3ffeb1638fc8a548fc2c0643d5a https://github.com/Kaiepi/p6-Digest-BubbleBabble/pull/1
- [x] [HTTP::Server::Tiny](https://modules.perl6.org/dist/HTTP::Server::Tiny) – Fail, Bisected: 862908896ee5fa632128fec82a8590abdce79ca9 https://github.com/rakudo/rakudo/pull/2717 ?
- [x] [I18N::LangTags](https://modules.perl6.org/dist/I18N::LangTags) – Fail, Bisected: 2683b3d0987a93a8e8dccca96bd4097ec221a49f https://github.com/rakudo/rakudo/issues/2999
- [x] [LMDB](https://modules.perl6.org/dist/LMDB) – Fail, Bisected: 235f14cd5138663c35f574a694e45b5bc0141031 https://github.com/rakudo/rakudo/issues/3015
- [x] [MessagePack](https://modules.perl6.org/dist/MessagePack) – Fail, Bisected: 91359141fb7501636b073ccaf6fb6598dc273bec https://github.com/rakudo/rakudo/issues/3000
- [x] [NativeHelpers::Blob](https://modules.perl6.org/dist/NativeHelpers::Blob) – Fail, Bisected: 862908896ee5fa632128fec82a8590abdce79ca9 https://github.com/rakudo/rakudo/pull/2717
- [x] [Net::OSC](https://modules.perl6.org/dist/Net::OSC) – Fail, Bisected: 2683b3d0987a93a8e8dccca96bd4097ec221a49f https://github.com/rakudo/rakudo/issues/2999
- [x] [Numeric::Pack](https://modules.perl6.org/dist/Numeric::Pack) – Fail, Bisected: 2683b3d0987a93a8e8dccca96bd4097ec221a49f https://github.com/rakudo/rakudo/issues/2999
- [x] [PDF::Content](https://modules.perl6.org/dist/PDF::Content) – Fail, Bisected: 6e3a4b9380b526314e1f749df8cc6d66f1b2509f https://github.com/rakudo/rakudo/issues/2865
- [x] [Pastebin::Shadowcat](https://modules.perl6.org/dist/Pastebin::Shadowcat) – Fail, Bisected: 3af3bde70eaed13b235bc55c54cf0ca604be6fcf https://github.com/rakudo/rakudo/issues/3012
- [x] [QM](https://modules.perl6.org/dist/QM) – Fail, Bisected: 35b69f074b9db3ffeb1638fc8a548fc2c0643d5a https://gitlab.com/uzluisf/quine-mccluskey/merge_requests/1
- [x] [RPi::Device::PiGlow](https://modules.perl6.org/dist/RPi::Device::PiGlow) – Fail, Bisected: 84b0e38048ff606ebd8515c14f250fc80bd6e53b https://github.com/rakudo/rakudo/issues/3011
- [x] [RPi::Device::SMBus](https://modules.perl6.org/dist/RPi::Device::SMBus) – Fail, Bisected: 84b0e38048ff606ebd8515c14f250fc80bd6e53b https://github.com/rakudo/rakudo/issues/3011
- [x] [Ranker](https://modules.perl6.org/dist/Ranker) – Fail, Bisected: 2683b3d0987a93a8e8dccca96bd4097ec221a49f https://github.com/rakudo/rakudo/issues/2999
- [x] [Test::Deeply::Relaxed](https://modules.perl6.org/dist/Test::Deeply::Relaxed) – Fail, Bisected: 7af0fb1c4cc49f7fbcf438e6428ccd8846014269 https://github.com/rakudo/rakudo/issues/3014
- [x] [WebSocket](https://modules.perl6.org/dist/WebSocket) – Fail, Bisected: 862908896ee5fa632128fec82a8590abdce79ca9 Fails because of HTTP::Server::Tiny

**Comment by ugexe** [comment]
`App::ecogen` is ok. It switched to using `JSON::Fast`, but one of the tests is still using the rakudo json parser.

**Comment by AlexDaniel** [comment]
@ugexe does it mean that a PR for that module is coming?

**Comment by vrurg** [comment]
HTTP::Server::Tiny and NativeHelpers::Blob – fixed with rakudo/rakudo@6c023546

**Comment by AlexDaniel** [comment]
All issues are now in separate tickets. I don't need this ticket anymore.

**Comment by AlexDaniel** [comment]
@ugexe I don't think it's fixed. Output:
```
The following candidates are already installed: App::ecogen
===> Searching for: App::ecogen
===> Found: App::ecogen:ver<0.0.7>:auth<github:ugexe> [via Zef::Repository::LocalCache]
===> Testing: App::ecogen:ver<0.0.7>:auth<github:ugexe>
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "en_GB.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
t/00-load.t ....... ok
Too few positionals passed to 'update-local-package-list'; expected at least 1 argument but got only 0 in sub-signature of parameter @metas
  in method update-local-package-list at /root/Blin/data/zef-data/store/Perl6-App--ecogen.git/9e71422bf1da9d1c3b3e86ae032dfe907ad18b3e/lib/App/ecogen.pm6 (App::ecogen) line 62
  in block <unit> at t/01-downgrade.t line 34

t/01-downgrade.t .. 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 4/4 subtests 

Test Summary Report
-------------------
t/01-downgrade.t (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 4 tests but ran 0.
Files=2, Tests=3,  6 wallclock secs ( 0.03 usr  0.02 sys +  4.89 cusr  0.36 csys =  5.30 CPU)
Result: FAIL
===> Testing [FAIL]: App::ecogen:ver<0.0.7>:auth<github:ugexe>
Failed to get passing tests, but continuing with --force-test
===> Installing: App::ecogen:ver<0.0.7>:auth<github:ugexe>
===> Install [OK] for App::ecogen:ver<0.0.7>:auth<github:ugexe>

1 bin/ script [ecogen] installed to:
/root/Blin/installed/App::ecogen_0.0.7/bin
```

**Comment by AlexDaniel** [comment]
Although locally it installs fine… hm. Not sure what's going on.

**Comment by ugexe** [comment]
Probably because I didn’t bump the version (since it was just a change in a
test). So maybe Blin had the previous revision cached still, test and all.
